import { openAlexOmniTreeUrl } from "./externalProjects";

export type ChartCatalogItem = {
  path: string;
  externalUrl?: string;
  eyebrow: string;
  title: string;
  description: string;
  source: string;
  accent: string;
};

export const chartCatalog: ChartCatalogItem[] = [
  {
    path: "/charts/openalex-concepts",
    externalUrl: openAlexOmniTreeUrl,
    eyebrow: "OpenAlex · Hierarchy",
    title: "Topics & Concepts Tree (2026)",
    description: "Explore the current OpenAlex topics and concepts hierarchy in the dedicated external project.",
    source: "OpenAlex Omni Tree · external project",
    accent: "#f05d23",
  },
  {
    path: "/charts/openalex-node-edge",
    eyebrow: "OpenAlex · Growth",
    title: "Node & Edge Statistics",
    description: "Compare annual nodes, edges, fields of study, and their connected-network subsets.",
    source: "openAlex_nobook_notypenull",
    accent: "#396afc",
  },
  {
    path: "/charts/openalex-entropy",
    eyebrow: "OpenAlex · Complexity",
    title: "Network Entropy",
    description: "Explore degree, structural, normalized structural entropy, and network size by discipline.",
    source: "OpenAlex entropy snapshots",
    accent: "#8a4fff",
  },
  {
    path: "/charts/wm-disruption",
    eyebrow: "Web of Science · Evolution",
    title: "Disruption by Discipline",
    description: "Follow discipline-level disruption and connected paper volume through time.",
    source: "WM annual aggregates",
    accent: "#00a896",
  },
  {
    path: "/charts/wikipedia-network",
    eyebrow: "Wikipedia · Network",
    title: "Subject Connection Tree",
    description: "A force-directed minimum spanning tree of top-level academic disciplines.",
    source: "Wikipedia subject relevance",
    accent: "#dc3f63",
  },
  {
    path: "/charts/wikipedia-article-count",
    eyebrow: "Wikipedia · Scale",
    title: "Article Count by Discipline",
    description: "Compare monthly article totals and net changes across Wikipedia academic disciplines.",
    source: "Wikipedia subject article snapshots",
    accent: "#d6a21d",
  },
  {
    path: "/charts/wikipedia-network-profile",
    eyebrow: "Wikipedia · Small World",
    title: "Network Profile",
    description: "Track path length, clustering, connected articles, and network coverage by quarter.",
    source: "Wikipedia quarterly networks",
    accent: "#347f72",
  },
  {
    path: "/charts/wikipedia-degree-entropy",
    eyebrow: "Wikipedia · Entropy",
    title: "Degree Distribution Entropy",
    description: "Explore quarterly degree entropy by network direction and hierarchy depth.",
    source: "Wikipedia degree entropy snapshots",
    accent: "#a24db0",
  },
  {
    path: "/charts/wikipedia-structural-entropy",
    eyebrow: "Wikipedia · Structure",
    title: "Structural Entropy",
    description: "Compare structural entropy and network density for Level 2 and Level 3 graphs.",
    source: "Wikipedia structural entropy snapshots",
    accent: "#4472a8",
  },
  {
    path: "/charts/mag-subject-entropy",
    eyebrow: "MAG · Entropy",
    title: "MAG Subject Entropy",
    description: "Follow entropy, average degree, and network scale from 1900 through 2020.",
    source: "Microsoft Academic Graph snapshot",
    accent: "#c2553d",
  },
  {
    path: "/charts/mag-citation-network",
    eyebrow: "MAG · Citation Network",
    title: "Discipline Citation Network",
    description: "Explore weighted discipline links in 2016 and 2017 by inbound or outbound direction.",
    source: "MAG directed-network snapshots",
    accent: "#f05d23",
  },
  {
    path: "/charts/mag-disruption-structure",
    eyebrow: "MAG · Disruption",
    title: "Disruption Structure",
    description: "Compare disruption across paper percentiles and inspect cross-discipline citation flows.",
    source: "MAG disruption snapshot",
    accent: "#8a4fff",
  },
  {
    path: "/charts/snapshots/mag-disruption-trend",
    eyebrow: "MAG · Disruption",
    title: "Disruption Trend by Year",
    description: "Compare yearly paper counts across verified disruptive, neutral, and consolidating ranges.",
    source: "MAG disruption trend historical cache",
    accent: "#dc3f63",
  },
  {
    path: "/charts/snapshots/mag-average-citations",
    eyebrow: "MAG · Citation Statistics",
    title: "Average Citations by Year",
    description: "Compare yearly average inbound and outbound citations, with an optional cited-paper filter.",
    source: "MAG citation-statistics API export",
    accent: "#396afc",
  },
  {
    path: "/charts/snapshots/mag-field-count",
    eyebrow: "MAG · Fields of Study",
    title: "Fields of Study by Year",
    description: "Track the average number of field labels assigned to papers across major disciplines.",
    source: "MAG field-statistics API export",
    accent: "#00a896",
  },
  {
    path: "/charts/snapshots/mag-node-edge",
    eyebrow: "MAG · Growth",
    title: "MAG Node & Edge Growth",
    description: "Compare cumulative paper nodes and citation edges across major disciplines.",
    source: "MAG cumulative network API export",
    accent: "#396afc",
  },
  {
    path: "/charts/snapshots/mag-citation-half-life",
    eyebrow: "MAG · Citation Aging",
    title: "Citation Decay Period",
    description: "Measure how long papers take to reach selected cumulative citation percentiles.",
    source: "MAG citation half-life API export",
    accent: "#d6a21d",
  },
  {
    path: "/charts/snapshots/mag-article-totals",
    eyebrow: "MAG · Scale",
    title: "MAG Articles by Discipline",
    description: "Switch between annual and cumulative article counts for major disciplines.",
    source: "MAG article statistics API export",
    accent: "#00a896",
  },
  {
    path: "/charts/snapshots/mag-author-statistics",
    eyebrow: "MAG · Authorship",
    title: "MAG Author Statistics",
    description: "Compare unique authors, authorships, and authored papers through time.",
    source: "MAG authorship API export",
    accent: "#8a4fff",
  },
  {
    path: "/charts/snapshots/mag-zero-citation",
    eyebrow: "MAG · Coverage",
    title: "Uncited Papers",
    description: "Inspect the annual or aggregate count and share of uncited papers.",
    source: "MAG citation coverage API export",
    accent: "#dc3f63",
  },
  {
    path: "/charts/snapshots/wikipedia-self-citation",
    eyebrow: "Wikipedia · Discipline Links",
    title: "Discipline Self-Citation",
    description: "Compare within-discipline links by direction and category depth.",
    source: "Wikipedia self-link API export",
    accent: "#347f72",
  },
  {
    path: "/charts/snapshots/wikipedia-core-scale",
    eyebrow: "Wikipedia · Core",
    title: "Core Discipline Scale",
    description: "Compare article, inbound-link, and outbound-link counts across hierarchy levels.",
    source: "Wikipedia core statistics API export",
    accent: "#4472a8",
  },
  {
    path: "/charts/snapshots/wm-network-scale",
    eyebrow: "Web of Science · Growth",
    title: "WM Network Scale",
    description: "Track node and edge totals, ratios, and annual increments from 1900 onward.",
    source: "WM network statistics API export",
    accent: "#c2553d",
  },
  {
    path: "/charts/snapshots/mag-top-cited-papers",
    eyebrow: "MAG · Citation Leaders",
    title: "Top-Cited Papers by Year",
    description: "Inspect annual citation histories for the most-cited papers in five major disciplines.",
    source: "MAG top-citation API export",
    accent: "#d6a21d",
  },
  {
    path: "/charts/snapshots/mag-reference-age",
    eyebrow: "MAG · Reference History",
    title: "Earlier Papers Cited Later",
    description: "Compare the publication years of papers cited after a selected cutoff year.",
    source: "MAG reference-history API export",
    accent: "#347f72",
  },
  {
    path: "/charts/snapshots/wikipedia-global-evolution",
    eyebrow: "Wikipedia · Evolution",
    title: "Wikipedia Global Evolution",
    description: "Explore twelve scale, editing, authorship, and content-length indicators.",
    source: "Wikipedia fitted-statistics API export",
    accent: "#396afc",
  },
  {
    path: "/charts/snapshots/wikipedia-article-length",
    eyebrow: "Wikipedia · Content",
    title: "Wikipedia Article Length",
    description: "View article word-count distributions using logarithmic or linear buckets.",
    source: "Wikipedia article-size API export",
    accent: "#8a4fff",
  },
  {
    path: "/charts/snapshots/wikipedia-words-links",
    eyebrow: "Wikipedia · Content Links",
    title: "Words and Outbound Links",
    description: "Compare discipline-level word totals, averages, and outbound-link measures.",
    source: "Wikipedia content-link API export",
    accent: "#00a896",
  },
  {
    path: "/charts/snapshots/wikipedia-reference-patterns",
    eyebrow: "Wikipedia · References",
    title: "Discipline Reference Patterns",
    description: "Contrast MAG and Wikipedia discipline references as trends or lag distributions.",
    source: "Wikipedia reference API export",
    accent: "#dc3f63",
  },
  {
    path: "/charts/snapshots/wikipedia-disruption-filter",
    eyebrow: "Wikipedia · Disruption",
    title: "Filtered Article Distribution",
    description: "Compare yearly article distributions under the archived disruption filter preset.",
    source: "Wikipedia disruption-filter API export",
    accent: "#4472a8",
  },
  {
    path: "/charts/snapshots/degree-distributions",
    eyebrow: "MAG / WM · Power Law",
    title: "Degree Distributions",
    description: "Compare sampled 2020 power-law degree distributions across MAG and Web of Science.",
    source: "MAG/WM degree API export",
    accent: "#f05d23",
  },
  {
    path: "/charts/snapshots/mag-degree-exponent",
    eyebrow: "MAG · Power Law",
    title: "MAG Degree Exponent",
    description: "Track yearly power-law exponents for six major disciplines.",
    source: "MAG degree API export",
    accent: "#d6a21d",
  },
  {
    path: "/charts/snapshots/mag-discipline-citation-flow",
    eyebrow: "MAG · Citation Flow",
    title: "Discipline Citation Flow",
    description: "Compare yearly outbound citation counts or shares from a selected discipline.",
    source: "MAG cross-discipline API export",
    accent: "#00a896",
  },
  {
    path: "/charts/snapshots/discipline-dependency",
    eyebrow: "MAG / Wikipedia · Dependency",
    title: "Discipline Dependency",
    description: "Explore inbound, outbound, and net dependency relationships for Biology.",
    source: "MAG/Wikipedia dependency API export",
    accent: "#8a4fff",
  },
  {
    path: "/charts/snapshots/wikipedia-category-half-life",
    eyebrow: "Wikipedia · Taxonomy",
    title: "Category Half-Life",
    description: "Compare how many years it takes for half of a category's descendants to change.",
    source: "Wikipedia category API export",
    accent: "#347f72",
  },
  {
    path: "/charts/snapshots/wikipedia-top-articles",
    eyebrow: "Wikipedia · Citation Leaders",
    title: "Top Wikipedia Articles",
    description: "Rank the fifty most-linked articles by discipline and snapshot year.",
    source: "Wikipedia top-article API export",
    accent: "#dc3f63",
  },
  {
    path: "/charts/snapshots/mag-small-world",
    eyebrow: "MAG · Small World",
    title: "MAG Small-World Network",
    description: "Compare annual, ranked-network, and connected-network metrics across five disciplines.",
    source: "MAG small-world service export",
    accent: "#00a896",
  },
  {
    path: "/charts/snapshots/wikipedia-directed-distance",
    eyebrow: "Wikipedia · Directed Paths",
    title: "Directed Discipline Distance",
    description: "Compare bidirectional path metrics between Biology and four other disciplines.",
    source: "Wikipedia small-world service export",
    accent: "#396afc",
  },
  {
    path: "/charts/snapshots/mag-distance-bubbles",
    eyebrow: "MAG · Discipline Distance",
    title: "Discipline Distance Bubbles",
    description: "Plot disciplines between Biology and Physics with bubble size representing article volume.",
    source: "MAG distance API export",
    accent: "#d6a21d",
  },
  {
    path: "/charts/snapshots/mag-distance-network",
    eyebrow: "MAG · Discipline Network",
    title: "MAG Distance Network",
    description: "Explore discipline proximity and article scale across eight historical snapshots.",
    source: "MAG distance API export",
    accent: "#f05d23",
  },
  {
    path: "/charts/snapshots/mag-self-citation-ranking",
    eyebrow: "MAG · Self Citation",
    title: "Self-Citation by Ranking Depth",
    description: "Compare internal citation shares as the ranked paper set grows in 5,000-paper steps.",
    source: "MAG self-citation API export",
    accent: "#347f72",
  },
  {
    path: "/charts/snapshots/mag-reference-age-average",
    eyebrow: "MAG · Citation Aging",
    title: "Average Reference Age",
    description: "Track the average age of outbound references, with optional zero-citation filtering.",
    source: "MAG reference-age API export",
    accent: "#d6a21d",
  },
];
